server {
  listen 80;
  location /api/ {
    proxy_pass http://api:8000/;
  }

  location /kb/ {
    proxy_pass http://kb:8080/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Prefix /kb;
  }

  location = /favicon.ico {
    access_log off;
    log_not_found off;
    return 204;
  }

  location / {
    proxy_pass http://frontend:80/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
  }
}
