/** Catálogo de testes aplicados ao módulo Cofre — espelha backend/tests/test_cofre_*.py e e2e/segredos.spec.js */
export const COFRE_TEST_CATALOG = {
  updated_at: '2026-06-29',
  comando: 'pytest tests/test_cofre_api.py tests/test_cofre_service.py -v',
  suites: [
    {
      id: 'api-init',
      grupo: 'API — integração',
      alvo: 'POST /v1/cofre/init',
      arquivo: 'backend/tests/test_cofre_api.py',
      classe: 'TestCofreInit',
      testes: [
        'sem_jwt_retorna_401',
        'analista_bloqueado_403',
        'admin_inicializa_com_sucesso',
        'service_name_retornado_na_resposta',
        'segunda_chamada_retorna_ja_inicializado',
        'overwrite_true_reinicializa',
      ],
    },
    {
      id: 'api-status',
      grupo: 'API — integração',
      alvo: 'GET /v1/cofre/status',
      arquivo: 'backend/tests/test_cofre_api.py',
      classe: 'TestCofreStatus',
      testes: [
        'sem_jwt_retorna_401',
        'analista_bloqueado_403',
        'status_nao_inicializado',
        'status_inicializado_apos_init',
        'status_contem_flag_vault_api_token',
      ],
    },
    {
      id: 'api-gravar',
      grupo: 'API — integração',
      alvo: 'POST /v1/cofre/segredos',
      arquivo: 'backend/tests/test_cofre_api.py',
      classe: 'TestCofreGravarSegredo',
      testes: [
        'sem_jwt_retorna_401',
        'grava_com_sucesso',
        'chave_reservada_retorna_422',
        'chave_vazia_retorna_422',
        'chave_so_espacos_retorna_422',
        'value_vazio_retorna_422',
        'vault_nao_inicializado_retorna_400',
        'chave_stripped_no_retorno',
      ],
    },
    {
      id: 'api-remover',
      grupo: 'API — integração',
      alvo: 'DELETE /v1/cofre/segredos/{key}',
      arquivo: 'backend/tests/test_cofre_api.py',
      classe: 'TestCofreRemoverSegredo',
      testes: [
        'sem_jwt_retorna_401',
        'chave_reservada_retorna_400',
        'remove_chave_existente',
        'chave_inexistente_removido_false',
        'key_retornado_na_resposta',
      ],
    },
    {
      id: 'api-resolver',
      grupo: 'API — integração',
      alvo: 'POST /v1/cofre/resolver',
      arquivo: 'backend/tests/test_cofre_api.py',
      classe: 'TestCofreResolver',
      testes: [
        'sem_x_vault_token_retorna_401',
        'token_errado_retorna_401',
        'vault_api_token_nao_configurado_retorna_503',
        'chave_reservada_retorna_400',
        'chave_inexistente_retorna_404',
        'retorna_valor_descriptografado',
        'resposta_nao_expoe_outros_campos',
      ],
    },
    {
      id: 'api-get',
      grupo: 'API — integração',
      alvo: 'GET /v1/cofre/segredos/{key}',
      arquivo: 'backend/tests/test_cofre_api.py',
      classe: 'TestCofreGetSegredo',
      testes: [
        'sem_x_vault_token_retorna_401',
        'token_errado_retorna_401',
        'vault_api_token_nao_configurado_retorna_503',
        'chave_reservada_retorna_400',
        'chave_inexistente_retorna_404',
        'retorna_valor_descriptografado',
        'resposta_contem_apenas_key_e_value',
        'equivalente_ao_post_resolver',
      ],
    },
    {
      id: 'svc-service-name',
      grupo: 'Serviço — unitário',
      alvo: '_vault_service_name()',
      arquivo: 'backend/tests/test_cofre_service.py',
      classe: 'TestVaultServiceName',
      testes: [
        'retorna_default_sem_env',
        'usa_valor_da_env',
        'env_vazia_usa_default',
        'env_so_espacos_usa_default',
      ],
    },
    {
      id: 'svc-init',
      grupo: 'Serviço — unitário',
      alvo: 'init_vault()',
      arquivo: 'backend/tests/test_cofre_service.py',
      classe: 'TestInitVault',
      testes: [
        'cria_master_key_retorna_true',
        'master_key_gravada_como_256_bits',
        'segunda_chamada_sem_overwrite_retorna_false',
        'segunda_chamada_sem_overwrite_preserva_master_key',
        'overwrite_true_retorna_true',
        'sem_keyring_retorna_false',
        'sem_crypto_retorna_false',
      ],
    },
    {
      id: 'svc-initialized',
      grupo: 'Serviço — unitário',
      alvo: 'vault_initialized()',
      arquivo: 'backend/tests/test_cofre_service.py',
      classe: 'TestVaultInitialized',
      testes: ['false_sem_master_key', 'true_apos_init', 'false_sem_keyring'],
    },
    {
      id: 'svc-write',
      grupo: 'Serviço — unitário',
      alvo: 'write_secret_to_vault()',
      arquivo: 'backend/tests/test_cofre_service.py',
      classe: 'TestWriteSecretToVault',
      testes: [
        'grava_blob_no_keyring',
        'blob_nao_contem_texto_em_claro',
        'levanta_runtime_sem_vault_inicializado',
        'levanta_runtime_sem_keyring',
        'levanta_valueerror_chave_vazia',
        'levanta_valueerror_chave_so_espacos',
      ],
    },
    {
      id: 'svc-read',
      grupo: 'Serviço — unitário',
      alvo: 'read_secret_from_vault()',
      arquivo: 'backend/tests/test_cofre_service.py',
      classe: 'TestReadSecretFromVault',
      testes: [
        'retorna_valor_descriptografado',
        'none_para_chave_inexistente',
        'none_sem_vault_inicializado',
        'none_para_chave_vazia',
        'none_sem_keyring',
        'none_sem_crypto',
        'none_para_blob_corrompido',
        'preserva_caracteres_especiais',
        'preserva_unicode',
        'write_read_round_trip',
      ],
    },
    {
      id: 'svc-delete',
      grupo: 'Serviço — unitário',
      alvo: 'delete_secret_from_vault()',
      arquivo: 'backend/tests/test_cofre_service.py',
      classe: 'TestDeleteSecretFromVault',
      testes: [
        'retorna_true_para_chave_existente',
        'chave_removida_nao_e_mais_lida',
        'retorna_false_para_chave_inexistente',
        'retorna_false_sem_keyring',
        'idempotente_duplo_delete',
      ],
    },
    {
      id: 'svc-get-secret',
      grupo: 'Serviço — unitário',
      alvo: 'get_secret()',
      arquivo: 'backend/tests/test_cofre_service.py',
      classe: 'TestGetSecret',
      testes: [
        'env_vence_vault_por_padrao',
        'vault_como_fallback_sem_env',
        'default_quando_ambos_ausentes',
        'none_quando_tudo_ausente',
        'prefer_vault_vault_vence_env',
        'prefer_vault_cai_em_env_se_vault_ausente',
        'env_vazia_tratada_como_ausente',
        'vault_vazio_tratado_como_ausente',
        'env_name_override',
        'vault_key_override',
      ],
    },
    {
      id: 'svc-describe',
      grupo: 'Serviço — unitário',
      alvo: 'describe_secret_resolution()',
      arquivo: 'backend/tests/test_cofre_service.py',
      classe: 'TestDescribeSecretResolution',
      testes: [
        'source_env_quando_so_env',
        'source_vault_quando_so_vault',
        'source_default_quando_apenas_default',
        'source_absent_quando_tudo_ausente',
        'value_exposed_sempre_false',
        'resolved_espelha_configured',
        'resolved_false_quando_absent',
        'env_vence_vault_sem_prefer_vault',
        'vault_vence_env_com_prefer_vault',
        'prefer_vault_refletido_no_resultado',
        'vault_service_name_refletido',
      ],
    },
    {
      id: 'e2e-segredos',
      grupo: 'E2E — Playwright',
      alvo: '/segredos-status',
      arquivo: 'frontend/tests/e2e/segredos.spec.js',
      classe: 'segredos.spec',
      testes: [
        'página Status de Segredos carrega com título correto',
        'botão Atualizar está visível',
        'botão Inicializar cofre está visível',
        'botão Gravar segredo está visível',
        'tabela de segredos é exibida após carregamento',
        'tabela tem cabeçalhos de coluna corretos',
        'valores dos segredos nunca são expostos',
        'card de resumo exibe totais numéricos',
        'chips de origem exibem tooltip ao passar o mouse',
        'botão Atualizar dispara recarga dos segredos',
        'seção Testes aplicados está visível',
      ],
    },
  ],
}

export function totalCofreTests() {
  return COFRE_TEST_CATALOG.suites.reduce((acc, suite) => acc + suite.testes.length, 0)
}

export function countCofreTestsByGrupo(prefix) {
  return COFRE_TEST_CATALOG.suites
    .filter((suite) => suite.grupo.startsWith(prefix))
    .reduce((acc, suite) => acc + suite.testes.length, 0)
}

export function formatTestName(name) {
  if (name.includes(' ')) return name
  return name.replace(/^test_/, '').replaceAll('_', ' ')
}
