"""Contratos de domínio independentes de infraestrutura."""

from app.domain.service_management import (
    Approval,
    ApprovalStatus,
    CaseEvent,
    EvidenceReference,
    ExternalReference,
    ExternalReferenceType,
    Impact,
    InvalidStateTransition,
    Service,
    ServiceCase,
    ServiceCasePriority,
    ServiceCaseState,
    ServiceCaseType,
    ServiceDependency,
    ServiceDependencyType,
    ServiceManagementValidationError,
    ServiceOffering,
    SlaPolicy,
    Urgency,
    calculate_priority,
)

__all__ = [
    'Approval',
    'ApprovalStatus',
    'CaseEvent',
    'EvidenceReference',
    'ExternalReference',
    'ExternalReferenceType',
    'Impact',
    'InvalidStateTransition',
    'Service',
    'ServiceCase',
    'ServiceCasePriority',
    'ServiceCaseState',
    'ServiceCaseType',
    'ServiceDependency',
    'ServiceDependencyType',
    'ServiceManagementValidationError',
    'ServiceOffering',
    'SlaPolicy',
    'Urgency',
    'calculate_priority',
]
