#!/usr/bin/env python3
"""Post-merge main runtime validator.

Validates the critical post-merge runtime evidence generated by existing ReqSys
operational workflows. This validator is intentionally small and offline: it
reads local artifacts, verifies their contracts and writes a single audit report.
"""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path
from typing import Any

DEFAULT_SMOKE = "artifacts/runtime-production-smoke-governed.json"
DEFAULT_EXECUTIVE = "artifacts/executive-runtime-evidence-summary/executive-runtime-evidence-summary.json"
DEFAULT_OUTPUT = "artifacts/post-merge-main-runtime-validator/post-merge-main-runtime-validator.json"


def load_json(path: str | Path) -> dict[str, Any]:
    file_path = Path(path)
    if not file_path.exists():
        return {}
    return json.loads(file_path.read_text(encoding="utf-8"))


def _status(value: Any, default: str = "unknown") -> str:
    text = str(value or default).strip().lower()
    return text or default


def _bool(value: Any) -> bool:
    return bool(value) is True


def validate_smoke(smoke: dict[str, Any]) -> dict[str, Any]:
    if not smoke:
        return {
            "id": "runtime_smoke",
            "status": "blocked",
            "ok": False,
            "detail": "runtime smoke artifact missing",
        }
    required_ok = int(smoke.get("required_ok") or 0)
    required_total = int(smoke.get("required_total") or 0)
    status = _status(smoke.get("status"))
    ok = status == "healthy" and required_total > 0 and required_ok == required_total
    return {
        "id": "runtime_smoke",
        "status": "passed" if ok else "blocked",
        "ok": ok,
        "detail": f"status={status} required={required_ok}/{required_total}",
        "base_url": smoke.get("base_url") or "",
        "required_success_percentual": smoke.get("required_success_percentual", 0),
    }


def validate_executive_summary(summary: dict[str, Any]) -> dict[str, Any]:
    if not summary:
        return {
            "id": "executive_runtime_evidence_summary",
            "status": "blocked",
            "ok": False,
            "detail": "executive summary artifact missing",
        }
    contract = summary.get("contract")
    status = _status((summary.get("summary") or {}).get("status"))
    production_ready = _bool((summary.get("summary") or {}).get("production_ready"))
    ok = contract == "executive-runtime-evidence-summary" and status in {"passed", "warning"} and "cards" in summary
    return {
        "id": "executive_runtime_evidence_summary",
        "status": "passed" if ok else "blocked",
        "ok": ok,
        "detail": f"contract={contract} status={status} production_ready={production_ready}",
        "production_ready": production_ready,
        "risk": (summary.get("summary") or {}).get("risk"),
    }


def _evidence_completeness_percentual(checks: list[dict[str, Any]]) -> float:
    if not checks:
        return 0.0
    passed = sum(1 for check in checks if check["ok"])
    return round((passed / len(checks)) * 100, 2)


def _dominant_blocker(failed: list[dict[str, Any]]) -> str:
    if not failed:
        return "none"
    return str(failed[0]["id"])


def _automatic_action(status: str, dominant_blocker: str) -> str:
    if status == "passed":
        return "publish_artifact_and_continue_increment_planning"
    if dominant_blocker == "runtime_smoke":
        return "rerun_post_merge_main_runtime_validator_after_runtime_stabilization"
    if dominant_blocker == "executive_runtime_evidence_summary":
        return "rebuild_executive_runtime_evidence_summary_and_rerun_validator"
    return "inspect_blocking_artifacts_and_rerun_validator"


def _human_action(status: str, dominant_blocker: str) -> str:
    if status == "passed":
        return "none"
    if dominant_blocker == "runtime_smoke":
        return "validate_public_runtime_url_or_environment_availability"
    return "review_missing_or_invalid_evidence_artifact"


def build_report(smoke: dict[str, Any], executive: dict[str, Any], *, repo: str, sha: str, run_id: str | None) -> dict[str, Any]:
    checks = [validate_smoke(smoke), validate_executive_summary(executive)]
    failed = [check for check in checks if not check["ok"]]
    status = "passed" if not failed else "blocked"
    dominant_blocker = _dominant_blocker(failed)
    return {
        "schema_version": "1.1.0",
        "contract": "post-merge-main-runtime-validator",
        "generated_at_epoch": int(time.time()),
        "repo": repo,
        "sha": sha,
        "github_run_id": run_id,
        "status": status,
        "risk": "low" if status == "passed" else "high",
        "evidence_completeness_percentual": _evidence_completeness_percentual(checks),
        "dominant_blocker": dominant_blocker,
        "automatic_action_possible": _automatic_action(status, dominant_blocker),
        "human_action_required": _human_action(status, dominant_blocker),
        "checks": checks,
        "blocking_issues": [item["id"] for item in failed],
        "links": {
            "repository": f"https://github.com/{repo}" if repo else "",
            "actions": f"https://github.com/{repo}/actions" if repo else "",
            "runtime_public_url": smoke.get("base_url") or "https://reqsys-app.fly.dev",
        },
        "guardrails": [
            "post_merge_main_scope",
            "artifact_contract_validation",
            "no_runtime_mutation",
            "reuse_existing_runtime_smoke",
        ],
    }


def render_markdown(report: dict[str, Any]) -> str:
    lines = [
        "# Post-merge Main Runtime Validator",
        "",
        f"- Status: `{report['status']}`",
        f"- Risk: `{report['risk']}`",
        f"- SHA: `{report['sha']}`",
        f"- Evidence completeness: `{report['evidence_completeness_percentual']}%`",
        f"- Dominant blocker: `{report['dominant_blocker']}`",
        f"- Automatic action possible: `{report['automatic_action_possible']}`",
        f"- Human action required: `{report['human_action_required']}`",
        "",
        "## Checks",
    ]
    for check in report["checks"]:
        lines.append(f"- `{check['status']}` {check['id']} — {check['detail']}")
    if report["blocking_issues"]:
        lines.extend(["", "## Blocking issues"])
        lines.extend(f"- `{item}`" for item in report["blocking_issues"])
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Validate post-merge main runtime evidence")
    parser.add_argument("--runtime-smoke", default=DEFAULT_SMOKE)
    parser.add_argument("--executive-summary", default=DEFAULT_EXECUTIVE)
    parser.add_argument("--repo", default="")
    parser.add_argument("--sha", default="")
    parser.add_argument("--github-run-id", default="")
    parser.add_argument("--output", default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    report = build_report(
        load_json(args.runtime_smoke),
        load_json(args.executive_summary),
        repo=args.repo,
        sha=args.sha,
        run_id=args.github_run_id or None,
    )
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    (output.parent / "summary.md").write_text(render_markdown(report), encoding="utf-8")
    print(json.dumps({"status": report["status"], "risk": report["risk"]}, ensure_ascii=False))
    return 0 if report["status"] == "passed" else 1


if __name__ == "__main__":
    raise SystemExit(main())
