global:
  resolve_timeout: 5m

route:
  receiver: dev-log
  group_by: [alertname, severity, environment]
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 4h

receivers:
  - name: dev-log

inhibit_rules:
  - source_matchers: [severity="critical"]
    target_matchers: [severity="warning"]
    equal: [alertname, environment]
